#!/bin/bash

set -e

. /etc/docker-container/env-defaults

USER=$(awk -v val=$UID -F ":" '$3==val{print $1}' /etc/passwd)

command_assets () {
  RAILS_ENV=$APP_ENV bundler exec rake assets:precompile
}

command_bundler () {
  if [ -f "Gemfile" ]; then
    RAILS_ENV=$APP_ENV bundler install
  else
    echo ":: Gemfile not found"
    exit 1
  fi
}

command_run () {
  if [ -d "public/assets" ]; then
    rm -rf public/assets > /dev/null 2>&1
  fi

  if [ "$APP_ENV" == "production" ]; then
    command_assets
  else
    sed -i '/ENV_PRODUCTION/d' /etc/nginx/sites-enabled/default
  fi

  RAILS_ENV=$APP_ENV bundler exec puma -d -C /etc/docker-container/puma.rb
  
  nginx

  exit 0
}

command_script () {
  if [ -f "${APP_HOME}/script/${1}.sh" ]; then
    . ${APP_HOME}/script/${1}.sh
    exit 0
  fi
}

if [ "$APP_BUNDLE" != "n" ]; then
  command_bundler
fi

case "$1" in 
  assets)
    command_assets
  ;;

  bundle|bundler)
    command_bundler
  ;;
  run)
    command_run
  ;;

  script)
    command_script "$2"
  ;;

  *)
    exec "$@"
  ;;
esac